const {mkRow}=mkTable(); const ok=T.ok;
T.head('bucketing');
spreadsheetData=[mkRow('Child Part','2','D-100'),mkRow('BO','3','BOP-1'),
  mkRow('Missing Drawing','1','D-404'),mkRow('','',''),mkRow('Child Part',''),mkRow('','7')];
let st=buildSubmitState();
ok('child bucket = 2', st.childParts.payload.length===2);
ok('bo bucket = 1', st.boParts.payload.length===1);
ok('incomplete rows skipped', st.childParts.payload.length+st.boParts.payload.length===3);
ok('missing drawing tracked', st.pdfs.remaining.length===1&&st.pdfs.remaining[0]==='D-404');
T.head('item numbering matches original formula');
ok('row0 -> 11', st.childParts.payload[0].itemNumber===11);
ok('row1 BO -> 12', st.boParts.payload[0].itemNumber===12);
ok('row2 -> 13', st.childParts.payload[1].itemNumber===13);
ok('max = 13', st.maxItemNumber===13);
ok('itemBase = 10', st.itemBase===10);
T.head('payload shape');
spreadsheetData[0]["Matched Childpart"]='D.1.0';
ok('dots stripped', buildSubmitState().childParts.payload[0].drawingNumber==='D10');
spreadsheetData[0]["Matched Childpart"]='D-100';
ok('bo field name', st.boParts.payload[0].boughtoutPartNumber==='BOP-1');
ok('ocrWarning carried', st.childParts.payload[0].ocrWarning==='OCR(Q)');
ok('_pRow recorded', typeof st.childParts.payload[0]._pRow==='number');
T.head('stripInternal');
const sent=stripInternal(st.childParts.payload);
ok('_pRow stripped', sent.every(r=>!('_pRow' in r)));
ok('fields survive', sent[0].quantity==='2'&&sent[0].itemNumber===11);
ok('source untouched', '_pRow' in st.childParts.payload[0]);
T.head('empty buckets');
spreadsheetData=[mkRow('BO','5','B1')]; st=buildSubmitState();
ok('no child -> skipped', st.childParts.status==='skipped');
ok('no missing -> pdfs skipped', st.pdfs.status==='skipped');
ok('bo -> todo', st.boParts.status==='todo');
T.head('physical vs visual rows');
spreadsheetData=[mkRow('Child Part','1','A'),mkRow('Child Part','2','B')];
_rowMap=[1,0]; st=buildSubmitState();
ok('_pRow = physical', st.childParts.payload[0]._pRow===1);
ok('itemNumber = visual', st.childParts.payload[0].itemNumber===11);
_rowMap=null;
T.head('divergedLockedRows');
spreadsheetData=[mkRow('Child Part','2','D-1')];
st=buildSubmitState(); st.childParts.status='done'; _submitState=st;
ok('clean = no divergence', divergedLockedRows().length===0);
spreadsheetData[0].Quantity.text='99';
ok('detects edited qty', divergedLockedRows().length===1);
spreadsheetData[0].Quantity.text='2'; spreadsheetData[0].Material.text='X';
ok('detects edited material', divergedLockedRows().length===1);
_submitState.childParts.status='failed';
ok('ignores non-done stages', divergedLockedRows().length===0);
T.done();
